# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fb450ce4d8885e36051ea6e868edce846aeb8861cfa5a5caec51a0909e4a81904d8f3f55865ebba86f81178bc174855ad69d9a0d0879ef816a765b286f020922

test:
  secret_key_base: ce5737f827b2cfd66fcbfc3faac0262fdb9cdc1ede79eb7557fa1a4f296584354371f654fae7568c3041c16844a7affedab416fcc2b4dd0dc8b8f090a7539939

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
